import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import ThemeProvider from '@/components/theme-provider';
import AuthProvider from '@/components/auth-provider';
import MaxWidthContainer from '@/components/max-width-container';
import Nav from '@/components/nav/nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <header className="w-full flex justify-center">
              <MaxWidthContainer className="fixed top-0  bg-background">
                <Nav />
              </MaxWidthContainer>
            </header>
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
